### ISSUE TITLE
Cloned and added additional functionality, if you're curious and want me to share.

### ISSUE THREAD

**Issue by prestonator** [Debupt/MidjourneyWrapper#3]
1. I added a flask endpoint so that the users of this app can send POST requests with the prompt.
2. I also added the ability to send the image somewhere once it is done generating using "requests.post"
4. And finally, I added the ability to automatically upscaled the image, save, and send (e.g. point 2.).

I'm not too experienced with contributing to repositories (none at all tbh haha), so just thought I'd share if you want the changes I added.

**Comment by prestonator** [comment]
I might use FastAPI instead of Flask for async and await implementation, actually.

**Comment by Debupt** [comment]
@prestonator , sorry for the late reply, I'm a little bit busy recently
great feature adding a flask endpoint, I plan to do a similar thing and integrate multiple image generative AIs
the snapshot as followings
![Selection_091](https://user-images.githubusercontent.com/11961243/232836945-9d35be95-bc70-43d0-9215-50935c6ee7f5.png)
